### ISSUE TITLE
Pneumaticcraft Agitator conflict

### ISSUE THREAD

**Issue by justinrusso** [Buuz135/DespawningSpawners#3]
There appears to be a crash involved when turning a mob spawner into an agitated mob spawner via PneumaticCraft.

In the referenced issue, a commenter stated:

>The simple workaround for this is to disable the "displaySpawnerParticle" option for the "Despawning Spawners" mod.

Crash Log: https://pastebin.com/eEmF1txK

Reference: https://github.com/Darkosto/SevTech-Ages/issues/1841

**Comment by desht** [comment]
This *should* be fixed in PNC:R v0.6.2, just released (we create a fake player to fool the spawner into spawning when no player is near, but it didn't have a valid ``connection`` field so Despawning Spawner's particle effects threw an exception).

**Comment by Buuz135** [comment]
Cool!
